### ISSUE TITLE
Problems compiling with Arduino

### ISSUE THREAD

**Issue by laura-james** [4tronix/Picobot2#1]
I've followed the instructions to install this library but keep getting the following error whenever i try to compile one of the example programs and upload to my Picobot2

 error: prototype for 'byte Picobot2::lineRead(bool)' does not match any in class 'Picobot2'

 byte Picobot2::lineRead(bool left)

Is there something I'm doing wrong?

this is the link to the full set of errors:
https://docs.google.com/document/d/15wJaTdLqUUSmM5cGY7s-JK335SCdHWWlCDJkvnzovzc/edit?usp=sharing_

**Comment by 4tronix** [comment]
It looks like you're running the old library with new application code. I'll check tomorrow when in the office, but it seems to have a library "...pre04" and it should be using the standard Picobot2 library

**Comment by laura-james** [comment]
Aha - I didn't realise I needed to delete those "..pre04" files from my library before using.
I've done that now and it's compiling fine now.
Thanks for the quick response
